// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbfybdwgxghnxmpdtlrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZnliZHdneGdobnhtcGR0bHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2Mjk2NTIsImV4cCI6MjA1NTIwNTY1Mn0.qr8lRVJtyDQj08B0xX3s2OwOYx-oRlMpysU30XKzAZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);