// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let clerkTokenFetcher: (() => Promise<string | null>) | null = null;

export const setClerkTokenFetcher = (fetcher: () => Promise<string | null>) => {
  clerkTokenFetcher = fetcher;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false,
    autoRefreshToken: false,
  },
  global: {
    fetch: async (url: RequestInfo | URL, options?: RequestInit) => {
      const headers = new Headers(options?.headers);

      if (clerkTokenFetcher) {
        try {
          const token = await clerkTokenFetcher();
          if (token) headers.set('Authorization', `Bearer ${token}`);
        } catch (error) {
          console.error('[Supabase Client] Error fetching Clerk token:', error);
        }
      }

      const response = await fetch(url, { ...(options ?? {}), headers });

      if (response.status === 401) {
        console.error('[Supabase Expert] 401 Unauthorized: Le JWT Clerk est rejete. Verifiez la synchronisation du JWT Secret dans le Dashboard Supabase.');
      }

      return response;
    },
  },
});
